### ISSUE TITLE
[BUG] auto complete is a bit up and down with working right

### ISSUE THREAD

**Issue by lewislepton** [Kode/KodeStudio#1]
recent mac osx updates for the past 2 commits have really knocked autocomplete on its side. it doesnt work great and is quite testy.
sometimes things work, other times, not

i did post about it before. but just making it known again ;)

**Comment by RobDangerous** [comment]
Not true, autocomplete on osx is currently not working at all. All you get is vscode's own "here are the words you typed before" autocomplete. Actual autocomplete will probably be back tomorrow.

PS: Sorry for loosing your previous issues. Recreated the repository so it isn't marked as a pure fork of vscode which made it not count the commits for the authors until they are merged back. Forgot about rescuing the issues :(

**Comment by lewislepton** [comment]
also to add. auto complete does not really work on new class files if the project has been built before adding it

**Comment by RobDangerous** [comment]
Should be better by now.
