### ISSUE TITLE
[BUG?] multiple memory

### ISSUE THREAD

**Issue by lewislepton** [Kode/KodeStudio#10]
having used the latest KS, noticed a few things and this last one was odd.
but on checking my activity monitor on mac, noticed all these helpers for KS
hink this is having an affect  on KS itself. just a thought

<img width="663" alt="screen shot 2016-08-15 at 00 17 47" src="https://cloud.githubusercontent.com/assets/11299322/17652777/e8e43bca-627d-11e6-89c9-1ff9279c1939.png">

**Comment by RobDangerous** [comment]
Regular vscode/chrome behavior AFAIK, but will see if I can do anything on my side to reduce that.

**Comment by RobDangerous** [comment]
Had a somewhat closer look, seems normal. Multiprocessy.
