### ISSUE TITLE
building a ios application from KS does bring errors in xcode

### ISSUE THREAD

**Issue by lewislepton** [Kode/KodeStudio#11]
lastest KS version

using the cmb+B which brings up a selection of all the the output capabilities. when choosing ios it does build, but in xcode, it errors out. screenshots given.
using terminal works completely fine though

<img width="315" alt="screen shot 2016-08-16 at 21 07 47" src="https://cloud.githubusercontent.com/assets/11299322/17714005/aadbec46-63f5-11e6-88af-8ad7ad1e0274.png">
<img width="253" alt="screen shot 2016-08-16 at 21 08 33" src="https://cloud.githubusercontent.com/assets/11299322/17714010/b0e6d07e-63f5-11e6-88fd-363aaa77af7c.png">

**Comment by RobDangerous** [comment]
Please try again.

**Comment by RobDangerous** [comment]
No feedback for two weeks :(
