### ISSUE TITLE
KodeStudio not working with old kha project

### ISSUE THREAD

**Issue by wighawag** [Kode/KodeStudio#12]
I tried running an project linked to an old Kha version but when I hit f5, I get the error :

```
Assets done.
Done.
Launch canceled.
```

note that `node Kha/make.js -t html5` and `node Kha/make.js --server`  works
`node Kha/make.js -t debug-html5` also works

see https://github.com/wighawag/spriter_test/issues/1
- VSCode Version: 16.7.1
- OS Version: Windows 10

Steps to Reproduce:
1. clone recursively : https://github.com/wighawag/spriter_test (Kha  is included)
2. open the folder 
3.  hit f5

**Comment by RobDangerous** [comment]
Older khamake versions had a bug and didn't return proper error codes, that's why the launch is canceled. Don't intend to put in a workaround in Kode Studio, sorry.

**Comment by wighawag** [comment]
no worries, I ll update the repo to latest kha anyway, just a matter of time :)
