### ISSUE TITLE
no error message when using older nodejs version or having error in khafile.js

### ISSUE THREAD

**Issue by wighawag** [Kode/KodeStudio#14]
- VSCode Version: 16.8.0
- OS Version: Windows

Steps to Reproduce:
1.  have node 5 installed
2.  launch app via F5
3. have an issue in khafile.js (like "return project;" instead of the new "resolve(project);")
4. launch app via F5

Both of these have proper error message upon launching them via khamake command line

**Comment by RobDangerous** [comment]
The resolve problem is hard to catch in Kode Studio - khamake checks for it when the process ends, but it doesn't end in Kode Studio.
But the node 5 thing is strange. Kode Studio doesn't use the installed node version (node is integrated in electron). Can you double check if old node versions really cause issues while inside Kode Studio?

**Comment by wighawag** [comment]
Ignore the node 5 thing then , because I fixed the node 5 first and then still got the issue but this was probably due to "resolve" missing. I am going to try on my current machine that is running node 4.

**Comment by wighawag** [comment]
I can confirm the node 5 is not an issue, only the resolve

**Comment by RobDangerous** [comment]
Should show a warning now when resolve is not called.
