### ISSUE TITLE
Debugging simple program no longer displaying as expected

### ISSUE THREAD

**Issue by thoughton** [Kode/KodeStudio#15]
- Kode Studio Version: 16.8.0
- OS Version: OS X 10.9.5

Since updating to this latest version of Kode Studio, I've noticed a very simple draw-a-triangle test program of mine no longer draws as expected when running from within Kode Studio.

Whereas previously the triangle would draw large and centered, it currently looks like this:

![Current](https://s12.postimg.org/aj05zo855/tri.png)

However, if I build and run the HTML5 target via the command line with the following commands:

```
node /Kode\ Studio.app/Contents/resources/app/extensions/kha/Kha/make html5
node /Kode\ Studio.app/Contents/resources/app/extensions/kha/Kha/make --server
```

When viewing it in Safari it looks exactly like I'd expect:

![Safari](https://s12.postimg.org/68li43321/tri_safari.png)

Please note, this is also exactly how it used to display via Kode Studio before the latest update.

Thanks!

**Comment by RobDangerous** [comment]
Not sure why that happens, can you provide the sample?

**Comment by thoughton** [comment]
Sure thing, I've just uploaded it here:
https://github.com/thoughton/kha-gl-01-triangle

**Comment by RobDangerous** [comment]
You forgot to call begin/end - things can randomly work when you don't do that but usually they don't.
render should be

```
private function render(framebuffer: Framebuffer): Void
{
    var g = framebuffer.g4;
    g.begin();

    // Bind the state to draw with
    g.setPipeline(m_pipelineState);

    // Bind the data to be drawn
    g.setVertexBuffer(m_vbo);
    g.setIndexBuffer(m_ibo);

    // Draw
    g.drawIndexedVertices();

    g.end();
}
`
```

**Comment by thoughton** [comment]
D'oh, that's embarrassing - thank you!

I guess I was caught out by the fact that it used to work before the recent update; but like you say, it seems like that was actually purely by chance...

Thanks again.

**Comment by RobDangerous** [comment]
It's a common error. Catching it automatically (at least using some kind of debug mode) is on my todo list.
