### ISSUE TITLE
[BUG FOUND] dropping autocomplete

### ISSUE THREAD

**Issue by lewislepton** [Kode/KodeStudio#17]
using the latest public release of KS

so i have had trouble with auto complete and was given a good way to find out how by @dstrekelj - using this in user settings

```
"haxe.displayServer": {
        "arguments": [
        "-v"
        ]
    }
```

on running this saw that things were not being picked up. but said this line when erroring after i had deleted the build file to compile again

```
Processing Arguments [--cwd,/Users/lepton/Developer/Kha/TESTS/DRAWWITHFORLOOP/build,project-debug-html5.hxml,-D,display-details,--no-output,--display,/Users/lepton/Developer/Kha/TESTS/DRAWWITHFORLOOP/Sources/Project.hx@276@type,-D,display-stdin]
> Error: Could not process argument project-debug-html5.hxml (file not found)
invalid character: -
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
```

so in my build file i see here its not seeing the file its looking for, because it puts `New` at the beginning
<img width="317" alt="screen shot 2016-09-21 at 21 36 40" src="https://cloud.githubusercontent.com/assets/11299322/18728083/822ce132-8043-11e6-915a-13ebc6a48375.png">

obviously deleting `New` does fix this. though do not know why its started

**Comment by lewislepton** [comment]
but once i do rebuild again, it now creates a second version with `New` in

**Comment by RobDangerous** [comment]
Uh, will try to replicate but never seen that happen myself.

**Comment by lewislepton** [comment]
its weird. i have no idea as to why. even downloaded new install and deleted everything from previous build. but still the same

**Comment by RobDangerous** [comment]
As just said in the chat, it's a recent khamake change (https://github.com/KTXSoftware/khamake/commit/72db4e69ea285d485b4dcd5bff8bb54622c1f695 and following commits). Will be fixed soonish.

**Comment by RobDangerous** [comment]
I can't really remember... is this fixed?

**Comment by lewislepton** [comment]
i think its ok. though. i guess maybe keep it around for a week or so. i dont have time to check right now. or just close, then open if it comes back?

**Comment by RobDangerous** [comment]
I'll get back to you in a week.

**Comment by lewislepton** [comment]
if i dont get back within that time. just close it.
lately have not been having problems. mainly things get slow once projects get big though. and have had to restart the haxe server quite a few times
