### ISSUE TITLE
Haxe Server crashes and will not be restarted

### ISSUE THREAD

**Issue by matthewswallace** [Kode/KodeStudio#18]
- VSCode Version: 16.8.0
- OS Version: OS X 10.11.6
  -Haxe Version: 3.3.0
  Steps to Reproduce:
1.  Start Kode Studio 
2. See message at top
   ![screen shot 2016-10-14 at 8 22 33 am](https://cloud.githubusercontent.com/assets/123816/19389008/d5136730-91e7-11e6-9e35-7ff5e473c080.png)

**Comment by RobDangerous** [comment]
Do you use the bundled Kha or do you have the khaPath option set or do you use a project local Kha? I see some open file there, what kind of project is that?

**Comment by RobDangerous** [comment]
I hope that was meanwhile fixed via more recent Haxe updates.
