### ISSUE TITLE
[BUG] the Assets keeps the red squiggle under the completed text

### ISSUE THREAD

**Issue by lewislepton** [Kode/KodeStudio#2]
something that has always been around. is that the red squiggle for say `Assets.images.picture;` always is below. it never goes away, even if it is right

**Comment by RobDangerous** [comment]
Also with the new Haxe extension?

**Comment by lewislepton** [comment]
yeah. seems to hang around

**Comment by RobDangerous** [comment]
That's weird, I think I've never seen any red squiggles at all with the new Haxe extension. Anyway, please have a look at the updates in the OS X repository.

**Comment by lewislepton** [comment]
that seems to have fixed it. though something else has cropped up - here https://github.com/KTXSoftware/KodeStudio/issues/5
