### ISSUE TITLE
Integrated console is slow and sometimes unresponsive

### ISSUE THREAD

**Issue by dstrekelj** [Kode/KodeStudio#20]
- VSCode Version: KodeStudio 16.8.0, Date 2016-08-24T14:57:48.456Z (https://github.com/KTXSoftware/KodeStudio/commit/c9038f8e16ebca8ffc83e6dd81e38f0bb8cf1cea)
- OS Version: Windows 10 64-bit

Steps to Reproduce:
1. Open KodeStudio
2. Open integrated terminal (View > Integrated Terminal)
3. Do stuff in the terminal

Notes:
- For reference, I'm using Visual Studio Code 1.6.1 (https://github.com/Microsoft/vscode/commit/9e4e44c19e393803e2b05fe2323cf4ed7e36880e) where the integrated terminal is performing just fine
- I'm using Git for Windows' `git-cmd.exe` for my integrated terminal, but the regular `cmd.exe` is slow as well

**Comment by RobDangerous** [comment]
Hm, let's try that again when Kode Studio caught up with vscode 1.6.1. Don't think I've done anything which could have influenced the terminal in any way.

**Comment by dstrekelj** [comment]
Fixed in latest release at the time of writing (https://github.com/KTXSoftware/KodeStudio/commit/90961d9c9e250262a6c80cc1f9b9928b265aa64e).
