### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by aammfe** [Kode/KodeStudio#23]
Hi
after changing path to git updated kha path getting this error . i have watched this video , [kha](https://youtu.be/2uF29dR14n4?t=469)

[debugger-for-chrome] Error processing "launch": Error: Cannot find module 'C:\HaxeToolkit\haxe\lib\kha\16,1,2\Tools\khamake\out\main.js'rl

**Comment by RobDangerous** [comment]
But that doesn't look like a git Kha path at all. Looks like a haxelib Kha path and that's not going to work.
