### ISSUE TITLE
Button for start debugging become disabled when there is already errors in the console

### ISSUE THREAD

**Issue by RafaelOliveira** [Kode/KodeStudio#24]
KS 16.11.0 for Windows.

The situation:
I start executing my code. The problem happen when there is errors in the code. In this case the error appear in the console, which is ok, but if I try to execute again, KS acts like the code is ok (even with errors). The bar in the top with play/stop button appear and I cant click in the stop button to hide it. I can't even try to execute again.

To summarize, the problem happen when there is errors in the console and you try to execute the code.

**Comment by dstrekelj** [comment]
I think I'm experiencing the same issue.

**Steps to reproduce:**
1. Write a piece of code with an error
2. Press F5, get told about the error
3. Fix the error
4. Press F5, nothing happens
5. Open debug sidebar, debugging option is greyed out
6. Restart KS or reload window to get it working

However, sometimes only F5 stops working and the debug button in the sidebar remains functional. After the debug runs successfully, F5 can be used again.
