### ISSUE TITLE
Syntax colouring issues with default dark theme

### ISSUE THREAD

**Issue by dstrekelj** [Kode/KodeStudio#25]
- VSCode Version: 16.11.0
- OS Version: Windows 10 64-bit

Steps to Reproduce:

1. Run KS 16.11.0 and look at Haxe code
2. Run KS 16.8.0 and look at Haxe code

Certain issues or changes in syntax colouring have appeared with the new KS release. Not sure if this even is an issue, but the latest stable release of the vshaxe plugin used with the latest stable release of VSCode does not produce the same syntax colouring results.

Here's how the syntax looks like in 16.8.0:

![](https://zippy.gfycat.com/AbleBrightArrowworm.gif)

Here's how the syntax looks like in 16.11.0:

![](https://zippy.gfycat.com/HighCorruptAardwolf.gif)

**Comment by RobDangerous** [comment]
Uhm, I'd say it looks better in 16.11? Can you show a pic of the latest vshaxe, too?

**Comment by dstrekelj** [comment]
Looks like the 16.11.0 syntax colouring is the correct one. Latest (git) vshaxe with latest stable VSCode gives that result.

At least I think I set up the git version properly. I'm not sure how to check.

But yeah, this probably isn't an issue, just a little unexpected quirk.

**Comment by RobDangerous** [comment]
But that means the quirk has actually been fixed, right?

**Comment by dstrekelj** [comment]
That would be my guess. Anyway, I think you can close this. It doesn't appear to have anything to do with KodeStudio.

**Comment by RobDangerous** [comment]
Okidoki!
