### ISSUE TITLE
[BUG] running of application continue when running window is closed

### ISSUE THREAD

**Issue by lewislepton** [Kode/KodeStudio#27]
current 16.11

on running a project, in HTML mode, not KROM, it persists to keep the 'application running' tab up, even though the window has been closed.
it wont go away either, you need to close KS completely  and start again

<img width="287" alt="screen shot 2016-11-18 at 19 13 14" src="https://cloud.githubusercontent.com/assets/11299322/20443115/613e5f2a-adc3-11e6-9fa1-f6a92445e24a.png">

**Comment by RobDangerous** [comment]
Is that a duplicate of #24?

**Comment by lewislepton** [comment]
actually no. seems to be a new bug.
this happens even with code that works. but at this moment its happening to me most if it works or errors.

**Comment by RobDangerous** [comment]
That other one was also a new bug, please have a closer look.

**Comment by lewislepton** [comment]
ill dig a bit further. though it feels like its linked though, same type of problem

**Comment by lewislepton** [comment]
also if its error[ed] but the window and taskbar go away. shortcuts dont work to run it again. you have to use the run button in the `Debug` mode
<img width="148" alt="screen shot 2016-11-18 at 20 13 07" src="https://cloud.githubusercontent.com/assets/11299322/20445047/7aa70d6a-adcb-11e6-9744-96054bfcc4a4.png">

**Comment by RobDangerous** [comment]
Still sounds much like that other issue.

**Comment by lewislepton** [comment]
aye. guess so. ill close this

**Comment by RobDangerous** [comment]
ok, let's check it again when the next version is here (in a few days).

**Comment by lewislepton** [comment]
will do ;)
