### ISSUE TITLE
[FEATURE] allow 'using' to be... used

### ISSUE THREAD

**Issue by lewislepton** [Kode/KodeStudio#28]
`using` does work. it just does not work in an autocomplete sense. would be cool ;)

<img width="184" alt="screen shot 2016-11-18 at 19 57 19" src="https://cloud.githubusercontent.com/assets/11299322/20444517/4122ab32-adc9-11e6-89a9-c5c34c8a653c.png">

**Comment by dstrekelj** [comment]
You might want to post that at the [vshaxe issue tracker](https://github.com/vshaxe/vshaxe/issues) instead.

**Comment by lewislepton** [comment]
actually yeah, you are right. will post ;)

**Comment by RobDangerous** [comment]
OK, closing here. Please check with current vshaxe, Kode Studio's vshaxe is a few months old.
