### ISSUE TITLE
With Krom debugging, the preview window closes right after compilation

### ISSUE THREAD

**Issue by trsh** [Kode/KodeStudio#31]
- VSCode Version: 16.11.1 
- OS Version: Windows 10 x64 

Steps to Reproduce:

1.  Open empty folder.
2.  Init new Project with "Init kha project"
3. Go to debug, choose Krom, and run

Using Kha from D:\Soft\Libaries\kha\Kha
Creating Kha project.
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-video.frag.glsl).
Compiling shader 7 of 8 (painter-text.vert.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Haxe compilation server stopped. **(IT CLOSES BY IT SELF)**

**Comment by RobDangerous** [comment]
Does it work, if you remove your khaPath setting? Very latest Kha is incompatible with Krom 16.11.1 because some functions were added.

**Comment by trsh** [comment]
@RobDangerous will try on Monday!

**Comment by trsh** [comment]
@RobDangerous OK, I had a try today and I confirm. It does work when I remove khaPath setting.

**Comment by RobDangerous** [comment]
Cool. And what you asked about in the chat - try again ala
```
function render2() {
    // your code
}

function render() {
    render2();
}

function init() {
    System.notifyOnRender(render);
}
```

Changes can currently not be applied to functions which were passed along as a variable.

**Comment by trsh** [comment]
@RobDangerous thanks! 

> Changes can currently not be applied to functions which were passed along as a variable.

I hope it will some day :)
