### ISSUE TITLE
"krom" target unavailable

### ISSUE THREAD

**Issue by anissen** [Kode/KodeStudio#32]
- VSCode Version: 16.11.1 (Kode Studio)
- OS Version: macOS 10.12

Steps to Reproduce:
1. Download, unzip and run Kode Studio 16.11.1 for Mac
2. Open an empty folder
3. Choose "Init Kha Project" from the command palette
4. Choose "Compile Kha Project" from the command palette

Observe: "krom" is not available as a target

Kode Studio outputs the following in its debug console which may or may not be related:
```
Conflict detected, command `workbench.action.toggleSidebarVisibility` cannot be triggered by cmd+b due to kha.compile
---
workbench.main.js:158816 [Extension Host] rejected promise not handled within 1 second
---
workbench.main.js:166333 Cannot read property 'endsWith' of undefined: TypeError: Cannot read property 'endsWith' of undefined
    at /private/var/folders/hz/8kbd2x9d0ps1jl55hbw0t9hm0000gn/T/AppTranslocation/D3648FE4-D7A8-4BDC-9913-0B78FD0D6BFC/d/Kode Studio.app/Contents/Resources/app/extensions/kha/Kha/Tools/khamake/out/main.js:254:27
    at next (<anonymous>)
    at fulfilled (/private/var/folders/hz/8kbd2x9d0ps1jl55hbw0t9hm0000gn/T/AppTranslocation/D3648FE4-D7A8-4BDC-9913-0B78FD0D6BFC/d/Kode Studio.app/Contents/Resources/app/extensions/kha/Kha/Tools/khamake/out/main.js:4:58)
```

**Comment by RobDangerous** [comment]
That is not how it works, Krom is an option in the debug panel (you can also deploy to Krom, but I want it to stabilize a little more before I expose that in Kode Studio).

**Comment by anissen** [comment]
Great, thanks for the explanation 👍
