### ISSUE TITLE
Error: Cannot cast HTMLImageElement to WebGLImage in Debug mode

### ISSUE THREAD

**Issue by malublu** [Kode/KodeStudio#34]
- VSCode Version (Kode Studio): 16.11.1
- OS Version: Windows 10 pro

Steps to Reproduce:
1. Code:
```
public function new() {
	Assets.loadEverything(loaded);
}

public function loaded() {
	_notLoaded = false;
	_ship = Assets.images.playerShip;
}

public function render(framebuffer: Framebuffer) {
	if(_notLoaded) return;
	var g =framebuffer.g2;
	g.begin();
	g.drawImage(_ship, 0, 0);
	g.end();
}
```
2. F5

Error:
```
Error: Cannot cast {
	g2canvas : null, 
	myWidth : 99, 
	myHeight : 75, 
	format : RGBA32, 
	renderTarget : false, 
	image : [object HTMLImageElement], 
	video : null
} to {
	__name__ : [kha,WebGLImage], 
	init : <function>, 
	upperPowerOfTwo : <function>, 
	formatByteSize : <function>
}
```

It works on the html5 target, but not in the debug html5 target with electron.
How to fix that?
Where is the target of this? (Source code) to help you out? i don't find it in kha or KodeStudio.

Thanks for your answer.

**Comment by RobDangerous** [comment]
You can set a breakpoint and step right into the source code. Do you use Kode Studio's integrated Kha? Can you provide a complete project so I can easier reproduce the issue?

**Comment by malublu** [comment]
Okay sorry i fix in my own code:
After some time (8h) i found the solution:
I created the Project before the window was avaible (before the callback: System.init(options, function () {).
I was wondering thats work on the html5 target but not in the debug mode of kode studio.
Now it works both.

Thank you for your help.
The Error message was a bit defficult to figure out what it means (where it comes from).

Should i make a pull request to create a error message if you loaded before the window is avaible?
