### ISSUE TITLE
Strange icon in titlebar on OS X 10.9.5

### ISSUE THREAD

**Issue by thoughton** [Kode/KodeStudio#37]
- VSCode Version: Kode Studio 1.8.1 (ebff2335d0f58a5b01ac50cb66737f4694ec73f3, 2017-01-29T09:52:56.006Z)
- OS Version: Darwin x64 13.4.0 (Mac OS X 10.9.5)

Steps to Reproduce:

1. Open existing project.
2. Notice strange "document" icon in titlebar:

![image](https://cloud.githubusercontent.com/assets/38389/22404800/151d2a5e-e630-11e6-89a0-56fa71145eca.png)

**Comment by RobDangerous** [comment]
I've never seen this myself, but hopefully some vscode update fixed this by now. Otherwise please reopen.
