### ISSUE TITLE
request for another 2017 build

### ISSUE THREAD

**Issue by qntf** [Kode/KodeStudio#40]
hi, i would like to request for another 2017 build? any chance we can get prebuilt latest please?
if you would prefer not to then ok too, i just requesting.

thank you very much rob,

**Comment by RobDangerous** [comment]
Will get to it right after the 1.11 release.

**Comment by lewislepton** [comment]
aye another build would awesome. vscode now has *PLAY THE FAN FARE* actual proper key layouts for DVORAK users. so can now actually use `cmd-/` to comment thing out. woooo

**Comment by qntf** [comment]
Hi @RobDangerous, any update on this?

Seems like a lot of major updates are out for VSCode, but the Kode Studio release is around 6 months old now. Could you please consider posting a new build?

**Comment by RobDangerous** [comment]
Sorry, already worked on it but turned out to be more complicated than expected. Don't have a good estimate yet.

**Comment by RobDangerous** [comment]
Finally!
