### ISSUE TITLE
[Request] investigate extension system and plausibility of having the extensions panel

### ISSUE THREAD

**Issue by nateupstairs** [Kode/KodeStudio#41]
- VSCode Version: 17.1
- OS Version: OSX Sierra

Steps to Reproduce:

1. Place 74th.vimStyle-0.5.0 in ~/.kodestudio/extensions
2. Extension works
3. Remove vimStyle
4. Place vscodevim.vim-0.7.1 in ~/.kodestudio/extensions
5. Extension doesn't work

These plugins are doing (roughly) the same thing, but only one of them seems to activate properly in kodestudio, and there's no panel in the IDE (as far as i know) to find what's enabled. So the idea would be to 1) possibly have the extensions panel back in case we need to click to enable something or see it's not activated, 2) see if there's a reason why some extensions might not activate.

**Comment by Jarrio** [comment]
In regards to extensions, one of the greatest things about vscode are extensions. It seems counter-intuitive to remove the ability to *easily* install them.

**Comment by RobDangerous** [comment]
Forked versions of vscode can't download extensions - or at least I couldn't get it to work yet. Still have to investigate.

**Comment by Jarrio** [comment]
That's unfortunate. Can I ask what made you go with a custom vscode version instead of bundling everything into an extension?

**Comment by RobDangerous** [comment]
When the first version of Kode Studio came out a lot of what it did wasn't possible in extensions. I think nowadays at least most of it is possible but haven't checked thoroughly (apart from reusing vscode's electron as a debug player, guess that will never be possible). Also there were no extension bundles so it would have been a mess.
But just in general, that's not how I work. I like doing fancy things and don't want to work in some artificially restricted environment. Building extensions is just the opposite of where I think Kode Studio will go. Long term I'm not even sure Kode Studio will still be a vscode fork (kodestudio.org sure isn't).
All of that said, I'm easily impressed by people taking initiative and if somebody builds Kode Studio into an extension bundle I will support that for sure. But I won't do it or maintain it myself.

**Comment by Jarrio** [comment]
Ah, that makes sense, I've added some basic Kha project creation with my own vscode extension and have just figured how to integrate regular vscode with krom which I've been debating on pushing as an update. I've been debating on whether I should push it at as a singular "Kha extension" or keep it as part of what I currently have.

In the end, I think it would have to be a separate Kha extension as we need to have the `Krom` executable and `krom-debug` extension bundled together. On that note, is debugging supposed to work for Krom? 

What are your thoughts on the future of a Kha IDE?

**Comment by RobDangerous** [comment]
So by now we also have the Kha Extension Pack as an alternative to Kode Studio which I think resolves this discussion.
