### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by OlegAntipov** [Kode/KodeStudio#42]
It's seems I cant refactor class\methods names in KodeStudio? F2 doesn't work for me...

**Comment by RobDangerous** [comment]
It's erroring now for me. Does that work in regular vshaxe?

**Comment by OlegAntipov** [comment]
frankly speaking personally I did not try, but here it is shown how it should work

https://github.com/vshaxe/vshaxe/wiki/Rename-Symbol

**Comment by RobDangerous** [comment]
Fixed.
