### ISSUE TITLE
Duplicate/spurious errors appear in Problems panel

### ISSUE THREAD

**Issue by thoughton** [Kode/KodeStudio#43]
- Version: Kode Studio 17.9.1
- OS Version: Mac OS X 10.9.5

Steps to Reproduce:

1. Open empty folder
2. Shift-cmd-P, select Init Kha Project
3. Open Sources/Project.hx in the Explorer tab
4. Add a call to "non_existing_function();" on line 14
5. Open Debug tab, select Start Debugging
6. Select Show Problems from the Error popup

Notice how 2 errors appear in the Problems panel.

Clicking on the first error will navigate to the problem line, as expected.

However, clicking on the second error shows an error popup about being unable to open a file. It looks like the file it is trying to open has incorrectly had the project path appended to it twice.

![screenshot](https://user-images.githubusercontent.com/38389/30785658-3811ac18-a162-11e7-8cfc-e6b0ad26a0eb.png)

**Comment by RobDangerous** [comment]
One error is from vshaxe, one is from the build output - so that's ok. But the path from the second one needs to be fixed.

**Comment by thoughton** [comment]
Ah yes, that makes sense regarding why there are two errors.

**Comment by sh-dave** [comment]
https://github.com/vshaxe/vshaxe/issues/23

**Comment by RobDangerous** [comment]
Fixed a while ago via the vshaxe update.
