### ISSUE TITLE
Can't debug projects or compile them to linux target on Manjaro (KodeStudio 17.9.1)

### ISSUE THREAD

**Issue by IMFUZZ** [Kode/KodeStudio#44]
Tried to run a basic new project in the new KodeStudio 17.9.1, white screen on HTML5 debug (though compiling directly to HTML5, opening the index.html works and shows the project rendering correctly) and won't compile on native linux target

- KodeStudio Version: 17.9.1
- OS Version: Manjaro 17.0.5 Gellivara

__Error while debugging with HTML5:__

Image: [https://i.imgur.com/AyRidpY.png](url)

DEBUG CONSOLE
```
SystemImpl.hx:327: Could not initialize WebGL 2, falling back to WebGL.
```
__Error message when compiling to linux target:__
DEBUG CONSOLE
```
../../../../../../Downloads/kode/resources/app/extensions/kha/Kha/Backends/Kore/khacpp/project/libs/std/Sys.winrt.cpp -o sys.winrt.o -static-libgcc -static-libstdc++ -pthread -lasound -ldl -lGL -lX11 -lXinerama

../../../../../../Downloads/kode/resources/app/extensions/kha/Kha/Backends/Kore/khacpp/project/libs/std/Sys.winrt.cpp:39:11: fatal error: xlocale.h: No such file or directory
 # include <xlocale.h>
           ^~~~~~~~~~~
compilation terminated.

make: *** [makefile:620: sys.winrt.o] Error 1

Compilation failed.
```

**Comment by RobDangerous** [comment]
Linux compilation error seems to be due to Kode/khacpp#1
The debug thing is strange though, WebGL 2 init shouldn't fail. Does the regular html5 build work in Chrome? (you'll have to start a server for Chrome, you can use node Kha/make --server to do that - I suspect you used Firefox when you opened index.html)

**Comment by IMFUZZ** [comment]
Put Kha in the failing project and tried running 
```
node Kha/make --server
```
The localhost:8080 runs perfectly in both Chrome and Firefox

(The index.html was opened in Chrome but also works perfectly fine in Firefox)

**Comment by IMFUZZ** [comment]
Edited the last post, ran the command in the wrong project :sweat_smile:

**Comment by IMFUZZ** [comment]
I have this logged in Chrome when accessing localhost:8080: 
```
kha.js:1335 SystemImpl.hx:327: Could not initialize WebGL 2, falling back to WebGL.
```

Firefox does not show that error

**Comment by RobDangerous** [comment]
So Chrome does indeed not like WebGL 2 on your system for some reason. But the fallback should work nonetheless. Try to add mainWindow.toggleDevTools(); in Kha/Tools/khamake/Data/debug-html5/electron.js after mainWindow.show(); - maybe that will show some additional error messages.

**Comment by thoughton** [comment]
I don't know whether relevant, but I see the exact same message when clicking `Start Debugging` in the `HTML5` Configuration on Mac OS X 10.9.5.

**Comment by IMFUZZ** [comment]
Retested on Nov 19, 2017 and everything seems to work.

(Edit): OS was re-installed and kodestudio re-downloaded

System info:
- OS: Manjaro 17.1pre2 Hakoila
- Kernel: x86_64 Linux 4.9.61-3-MANJARO

Kodestudio info:
- Version 17.9.1
- Commit 0eb40ad2cd45f7b02b138b1a4090966905ed0fec
- Date 2017-09-24T12:05:29.422Z
- Shell 1.6.6
- Renderer 56.0.2924.87
- Node 7.4.0
- Architecture x64
