### ISSUE TITLE
auto-import unresolved identifier

### ISSUE THREAD

**Issue by OlegAntipov** [Kode/KodeStudio#50]
perhaps it is worth adding auto-import of unresolved identifier? like here https://github.com/vshaxe/vshaxe/wiki/Code-Actions#import-actions

**Comment by RobDangerous** [comment]
Well, just try it maybe (Kode Studio uses vshaxe and all of that stuff works).

**Comment by OlegAntipov** [comment]
> Kode Studio uses vshaxe and all of that stuff works

is there any way to update vshaxe extension in the already installed kode studio?

**Comment by RobDangerous** [comment]
As I said, that stuff works, I just checked. See the description in your link to see how. vshaxe in Kode Studio is newer than the last change of that wiki page.

**Comment by OlegAntipov** [comment]
Oh, sorry, it's my fault. I used 17.1 version of Kode Studio. In 17.9.1 this feature works well.
