### ISSUE TITLE
Empty project build failed when build for linux on linux

### ISSUE THREAD

**Issue by ks-zealot** [Kode/KodeStudio#55]
- VSCode Version: Kode Studio 17.9.1
- OS Version: Linux   4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

Steps to Reproduce:

1. Open folder
2. Create project
3. Compile for Linux

Result : ../../../../../resources/app/extensions/kha/Kha/Kore/Backends/System/Linux/Sources/Kore/Sound.cpp:3:28: fatal error: alsa/asoundlib.h: No such file or catalog
 #include <alsa/asoundlib.h>
Full log : https://pastebin.com/0TGHQK5w

Reproduces without extensions: Yes

**Comment by RobDangerous** [comment]
Install asound. https://github.com/Kode/Kha/wiki/Linux has a list of apt commands for you.

**Comment by ks-zealot** [comment]
Yes, my bad, thank you
