### ISSUE TITLE
Unable to open Kodestudio - Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by rebootandfork** [Kode/KodeStudio#56]
- VSCode Version: 1.24.0
- OS Version: Ubuntu 14.04 x64

Steps to Reproduce:

1. opening kodestudio brings out error as in uploaded screenshot file.
![kodestudio](https://user-images.githubusercontent.com/745081/41340927-1c997e48-6f16-11e8-9ffa-5d38a3e759e5.png)
2. In terminal following lines would come out 
`aa@KEL:~/Downloads/KodeStudio-linux64$ ./kodestudio`
`bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
/home/aa/Downloads/KodeStudio-linux64/kodestudio --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=61027970542071A868EE9645890A472F --lang=en-GB --node-integration=true --background-color=#1E1E1E --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --service-request-channel-token=61027970542071A868EE9645890A472F --renderer-client-id=4 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd: relocation error: /home/aa/Downloads/KodeStudio-linux64/resources/app/node_modules/native-keymap/build/Release/keymapping.node: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE14_M_replace_auxEmmmc, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
[main 14:21:59] [VS Code]: render process crashed!
`

**Comment by RobDangerous** [comment]
Requires a newer libstdc. Will compile the next Linux version in 14.04 to hopefully fix this.

**Comment by RobDangerous** [comment]
Did as I said, hopefully that fixed it.
