### ISSUE TITLE
letters dont display correctly

### ISSUE THREAD

**Issue by FlameX12** [Kode/KodeStudio#58]
I am trying to use kodestudio on linux mint 19. Whenever I open kodestudio, all the letters are mangled. Can anyone help me fix this?

Here is a picture of the problem: https://i.imgur.com/ZcwZfdV.png

**Comment by RobDangerous** [comment]
Does vscode work for you?

**Comment by FlameX12** [comment]
@RobDangerous yes, the problem does not happen in vscode.

**Comment by RobDangerous** [comment]
I guess updating it to a new vscode version will fix it then. You can use the [Kha extension pack](https://marketplace.visualstudio.com/items?itemName=kodetech.kha-extension-pack) until I do so.

**Comment by FlameX12** [comment]
ok. thank you so much

**Comment by vivichrist** [comment]
I have Ubuntu 18.04 and there is something wrong with... the kerning? or something you can see parts or slivers of the neighbouring fonts which makes developing code very difficult.

**Comment by RobDangerous** [comment]
Same suggestion for you.

**Comment by RobDangerous** [comment]
Should be fixed now.
