### ISSUE TITLE
"Compile Kha Project" command is gone

### ISSUE THREAD

**Issue by Klug76** [Kode/KodeStudio#59]
Kode Stduio: 18.9.2
OS Version: Windows 7

Steps to Reproduce:

1. Create new project
2. Hit F1, enter Kha and ... here is no "Compile Kha Project".
(may be http://kha.tech/getstarted is outdated?)
3. Not clear how to create windows, android, ios or flash build configuration from Kode Stuido.

**Comment by RobDangerous** [comment]
The get started page was outdated. Fixed it, thanks for reporting it.
