### ISSUE TITLE
kha.khaPath doesn't work on Windows 10

### ISSUE THREAD

**Issue by peteshand** [Kode/KodeStudio#6]
- VSCode Version: 16.1
- OS Version: Windows 10

Steps to Reproduce:
1. open a new project
2. go to user settings
3. add "kha.khaPath":"path to git version of kha"
4. Kode Studio version of kha is still being used

**Comment by RobDangerous** [comment]
Yes, that feature was introduced post 16.1. You can get a dev version at https://github.com/KTXSoftware/KodeStudio-win32

**Comment by peteshand** [comment]
Oh cool.. thanks
