### ISSUE TITLE
Can't debug with Krom

### ISSUE THREAD

**Issue by DimPal2k** [Kode/KodeStudio#60]
Last version (Kode Studio 18.9.2 for Windows)
Works ok with Electron debugging, but Krom silently does nothing :(
I'd tried to run Krom.exe manualy, it requres api-ms-win-core-console-l2-1-0.dll
There is no such file in KodeStudio folders. I see api-ms-win-core-console-l1-1-0.dll, but it's just similar name.

**Comment by RobDangerous** [comment]
Windows 7, right? That's already fixed, but haven't recompiled Krom since.

**Comment by DimPal2k** [comment]
Win7 SP1

**Comment by RobDangerous** [comment]
As expected. Fix will be in the next release.

**Comment by RobDangerous** [comment]
Fixed.
