### ISSUE TITLE
Cannot watch values when debugging Haxe (Armory3D project)

### ISSUE THREAD

**Issue by StrayEddy** [Kode/KodeStudio#61]
I cannot watch any values, it always shows me this.

![image](https://user-images.githubusercontent.com/699437/50370282-f74d6a80-0571-11e9-8398-5f728bbb6c51.png)

Info:

![image](https://user-images.githubusercontent.com/699437/50370313-7d69b100-0572-11e9-990a-4919feade311.png)

Steps to Reproduce:

1. debug Armory3D project in haxe
2. try to watch a variable by hovering it.

**Comment by RobDangerous** [comment]
That's an old release of Kode Studio. If you get the same problem with the current release please reopen, provide more details (most importantly what debug target you are using) and check with a regular Kha project (I don't use Armory3D myself).
