### ISSUE TITLE
vscode 1.31 ( insider )

### ISSUE THREAD

**Issue by limbo127** [Kode/KodeStudio#62]
Hello, 
on fedora 29 ( linux / wayland ) stable visual studio does not start ( no display ) . 
It seems this is correct with visual studio 1.31 ( insider ).
How can I use kha ide with studio 1.31 

Regards, 
Nicolas Prochazka

**Comment by RobDangerous** [comment]
Easy: https://marketplace.visualstudio.com/items?itemName=kodetech.kha-extension-pack

**Comment by limbo127** [comment]
sorry, but it does not work for me.
installation of kha-extension-pack under linux, all seems to be ok exect that init Kha does not create build task.
regards, 
Nicolas

**Comment by RobDangerous** [comment]
Worked fine on Linux last time I tried. Sorry, you're free to try to fix it and send a pull request but I'm not going to debug the extensions in a vscode pre-release. Proper release will be soon enough anyways.

**Comment by RobDangerous** [comment]
And surprise, proper release doesn't look very proper, see Microsoft/vscode#67990 (thanks for looking into it right away, gama).
