### ISSUE TITLE
Port to VS Code 1.3+

### ISSUE THREAD

**Issue by LaurentOngaro** [Kode/KodeStudio#63]
Hi,
I'm using VScode and the fantastic [Material theme](https://material-theme.site/). But the [VS extension](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme) for this theme is not compatible with vscode 1.2.29 and previous.

It could be great if you can update Kode Studio to 1.3.0 and more versions of VS Code.

Thank for your great work

**Comment by RobDangerous** [comment]
It's bound to happen, every Kode Studio version is based on the most recent vscode version at the time of its release.

**Comment by LaurentOngaro** [comment]
thanks, for that. 
If someone is interested, I've created an extension that uses the color settings of that theme 
It can be used in VScode 1.29-  (and in Kode Studio 18.1).
Can be found here
https://gitlab.com/vscodedev/gameamea-vs-themes
