### ISSUE TITLE
Missing files on Linux release of Kode Studio 18.11

### ISSUE THREAD

**Issue by N8n5h** [Kode/KodeStudio#64]
- OS Version: Ubuntu 18.04.2

I downloaded [the release of Kode Studio 18.11 for Linux](https://github.com/Kode/KodeStudio/releases/download/v18.11/KodeStudio-Linux.tar.xz) and when I tried to open Kode Studio with: ./kodestudio, it failed to open with the next error message:
./kodestudio: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory.

**Comment by RobDangerous** [comment]
Looks like that was kicked out of recent Ubuntu releases. Just install libgconf manually.
