### ISSUE TITLE
Does not work on macOS

### ISSUE THREAD

**Issue by RblSb** [Kode/KodeStudio#66]
OS Version: 10.14.6

Steps to Reproduce:
1. Download Kode Studio 18.11 from github
2. Open any empty folder as project (Cmd-O)
3. F1 - Init kha project
4. Select debug tab and click on gear with orange circle to select configuration Electron
5. Click green run icon and get this:
![image](https://user-images.githubusercontent.com/8753432/67408190-4fedf980-f5c1-11e9-9416-e1de32237d50.png)

To restart configuration select remove `.vscode` inside project folder.
For Krom configuration you will get: `Configured debug type 'mock' is not supported.`
For Flash you will get: `Cannot find /Users/maksim/Documents/f/bin/your.swf`
`More...` in this list button does nothing.

**Comment by RblSb** [comment]
Extension pack works fine

**Comment by pyrofolium** [comment]
I get the same exact issue. Sceenshot: 

<img width="1107" alt="Main_hx_—_haxe_learn" src="https://user-images.githubusercontent.com/1806857/85892155-44cd1800-b7a5-11ea-9dff-0e8a05757c17.png">
