### ISSUE TITLE
[BUG?] auto complete gets knocked out

### ISSUE THREAD

**Issue by lewislepton** [Kode/KodeStudio#9]
it seems that the latest version of kode studio does work very well, but every now and again, the auto complete just goes away. dont know why, but its not possible. sometimes this could be from changing something to often.
say like
`graphics.something` and changing the 'something' to much knocks it out. a restart of KS fixes it though

**Comment by thoughton** [comment]
I've noticed this too.  I don't know whether changing 'something' regularly caused it for me too; but I certainly do rely on the auto-complete a lot, so it would've been popping-up frequently previously. A restart of the application fixes it for me also.

**Comment by RobDangerous** [comment]
Didn't change anything related to that but maybe the vshaxe update fixes it. Please give it another try.

**Comment by RobDangerous** [comment]
No feedback for two weeks :(
